Feature/redux
limanovic/to-do-list pull request #4
Opened 2023-05-16 14:02 UTC by limanovic

2023-05-16 14:25 UTC, asapMaki requested changes

2023-05-16 14:25 UTC, asapMaki commented on src/app/components/Input/AddTask.tsx
> +        if (changedName.length < 1 || changedName.trim() == '') alert('Task cannot be empty');
!changedName.trim()

2023-05-16 14:25 UTC, asapMaki commented on src/app/components/Input/AddTask.tsx
> +        if (changedName.length < 1 || changedName.trim() == '') alert('Task cannot be empty');
!changedName.length

2023-05-16 14:25 UTC, asapMaki commented on src/app/components/Redux/reducers.tsx
> +import taskReducer from './addTaskSlice';
create folder tasks and file in it called slice.ts

2023-05-16 14:25 UTC, asapMaki commented on src/app/components/Task/Task.tsx
> +    isEditing: string | null;
can be isEditing?:

2023-05-16 14:25 UTC, asapMaki commented on src/app/components/Task/Task.tsx
>      const [removeModal, setRemoveModal] = useState<boolean>(false);
reanme to modalOpened

2023-05-16 14:25 UTC, asapMaki commented on src/app/components/Input/AddTask.tsx
> +    const [saveModal, setSaveModal] = useState<boolean>(false);
rename to modalOpened, unless you have multiple modals

2023-05-17 10:32 UTC, asapMaki requested changes

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +    let tasks = useSelector((state: RootState) => state.tasks);
https://redux-toolkit.js.org/tutorials/typescript
Check in mobile repo for usage

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +import { TaskType, RootState } from './Redux/types';
type Task = ...

import { Task as TaskType ...

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +import { TaskType, RootState } from './Redux/types';
Talk with Davud

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +    const [taskName, setTaskName] = useState({ name: '', id: 0 });
in constants create initial task object to use throughout the apps

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +        setTaskName({ name: '', id: 0 });
initial task constant

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +        else setmodalOpened(true);
setModalOpened*

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
>      const inputChangeNotConfirmed = () => {
maybe name cancel ?

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
>      const inputChangeConfirmed = () => {
save or confirm ?

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +                    <button onClick={openmodalOpened} className="p-2 bg-[#2E7D32] text-white rounded">
research camel case naming convention

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/Redux/tasks/slice.tsx
> +import { TaskType } from '../types';
Task

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/Redux/tasks/slice.tsx
> +export const { addTask, removeTask, editTask, saveTask } = taskSlice.actions;
nice

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/Redux/types.tsx
> +export interface RootState {
checkout documentation for TS

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/Task.tsx
> +    const handleRemoveTask = (e: TaskType) => {
handleRemoveTask no need to pass any parameters when you already have task available in scope.
Learn arrow functions

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/Task.tsx
>                      onConfirm={() => handleRemoveTask(task)}
onConfirm={handleRemoveTask}

2023-05-17 10:32 UTC, asapMaki commented on src/app/components/TaskList.tsx
> +                {tasks?.map((task: TaskType) => (
Do you need type when store is already typescript compliant

2023-05-17 10:55 UTC, asapMaki requested changes

2023-05-17 10:55 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +    const [taskName, setTaskName] = useState<TaskType>();
is it name (string) or whole Task

2023-05-17 10:55 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +    const [modalOpened, setModalOpened] = useState<boolean>(false);
if you don't put false, what value will it be ?

2023-05-17 10:55 UTC, asapMaki commented on src/app/components/AddTask.tsx
>      const inputChangeNotConfirmed = () => {
+1

2023-05-17 10:55 UTC, asapMaki commented on src/app/components/Task.tsx
> +                <ConfirmModal openModal={modalOpened} onConfirm={handleRemoveTask} onCancel={notConfirmed} />
is openModal function or boolean (modalOpened)

2023-05-17 10:58 UTC, limanovic commented on src/app/components/AddTask.tsx
> +    const [taskName, setTaskName] = useState<TaskType>();
whole task

2023-05-18 03:33 UTC, asapMaki requested changes

2023-05-18 03:33 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +        setNewTask({ name: '', id: 0 });
in constants, or reducer, create variable emptyTask { name: '', id: 0 }

2023-05-18 03:33 UTC, asapMaki commented on src/app/components/Task.tsx
> +            {modalOpened && <ConfirmModal openModal={true} onConfirm={handleRemoveTask} onCancel={notConfirmed} />}
openModal={true}  if it is always true, do you need it ?

2023-05-18 03:35 UTC, asapMaki commented
I love the test section, why not make it as a list or something more readable
<img width="657" alt="image" src="https://github.com/limanovic/to-do-list/assets/30200380/0e2b1d3e-c4de-4fd8-b770-a7ef1cf2e139">

2023-05-18 03:35 UTC, asapMaki commented
https://to-do-list-q16cx2q1x-limanovic.vercel.app/

2023-05-18 08:03 UTC, asapMaki requested changes

2023-05-18 08:03 UTC, asapMaki commented on src/app/components/TaskList.tsx
> +        setModalOpened(false);
call closeModal() or as you name it notCOnfiremd

2023-05-18 08:03 UTC, asapMaki commented on src/app/components/TaskList.tsx
> +                {tasks.length > 1 && (
tasks.length > 1 - replace with different type of check truthy falsy values

2023-05-18 09:01 UTC, asapMaki requested changes

2023-05-18 09:01 UTC, asapMaki commented on src/app/components/Task.tsx
> +            {openModal && <ConfirmModal onConfirm={handleRemoveTask} onCancel={closeModal} />}
does this modal have its own animations ? 
With this approach you are blocking those animations

2023-05-18 09:01 UTC, asapMaki commented on src/app/components/Task.tsx
> +            {openModal && <ConfirmModal onConfirm={handleRemoveTask} onCancel={closeModal} />}
Why this instead of passing openModal variable as a prop?

2023-05-18 09:01 UTC, asapMaki commented on src/app/components/TaskList.tsx
>      const [modalOpened, setModalOpened] = useState<boolean>();
use this var name in component before

2023-05-18 09:29 UTC, asapMaki requested changes

2023-05-18 09:29 UTC, asapMaki commented on src/app/components/AddTask.tsx
> +                onConfirm={inputChangeConfirmed}
still thing inputChangeConfirmed doesn't describe what it actually does

2023-05-18 11:33 UTC, asapMaki approved these changes

2023-05-24 07:50 UTC, merged